version: '3'

services:
  database:
    container_name: neo4j_database
    image: neo4j:5.11
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
      # - NEO4J_dbms__memory__transaction__total__max
    volumes:
      - ./data:/data:rw
      - ./logs:/logs:rw
      - ./import:/import
      - ./conf:/conf
    networks:
      - default

  dashboard:
    container_name: neodash
    image: neo4jlabs/neodash:2.3.4
    ports:
      - "5005:5005"
    networks:
      - default
  
networks:
  default:
