version: '3'

services:
  database:
    container_name: neo4j_database
    image: neo4j:5.11
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
      - NEO4J_server_default__listen__address=0.0.0.0
      # - NEO4J_dbms__memory__transaction__total__max
    volumes:
      - ./data:/data:rw
      - ./logs/neo4j:/logs/neo4j:rw
      - ./import:/import
      - ./conf:/conf
    networks:
      - default
    restart: always

  api:
    container_name: graph_db_api
    build:
      context: ./services/api
      dockerfile_inline: |
        FROM python:3.9-slim-bullseye
        WORKDIR /wd
        COPY requirements.txt .
        RUN pip install --no-cache-dir -r requirements.txt
    volumes:
      - ./logs/api:/var/log/api
      - ./services/api/:/wd
    ports:
      - 5005:5005
    networks:
      - default
    command:
      sh -c "echo Running in Development &&
            uvicorn main:app --reload --host 0.0.0.0 --port 5005 --reload > /var/log/api/api.log 2>&1"
    restart: always

  ui:
    container_name: react_ui
    build:
      context: ./services/ib-graph-explorer
      dockerfile_inline: |
        FROM node:16-alpine
        WORKDIR /app
        COPY . /app
        COPY ./.ssh /root/.ssh
        RUN chmod 600 /root/.ssh/id_rsa.pub
        RUN chmod 600 /root/.ssh/id_rsa
        RUN chmod 777 /app/package-lock.json
        RUN npm install
        RUN npm install graphology-layout-forceatlas2
        RUN npm install react-cytoscape
        CMD ["npm", "start"]
    ports:
      - 3000:3000
    volumes:
      - ./services/ib-graph-explorer/src:/app/src:rw
      - ./services/ib-graph-explorer/public:/app/public:rw
      - ./logs/npm:/root/.npm
    environment:
      - CHOKIDAR_USEPOLLING=true
      - ESLINT_NO_DEV_ERRORS=true


networks:
  default:
